### ISSUE TITLE
Unable to convert to multisite.

### ISSUE THREAD

**Issue by samrueby** [Azure/wordpress-linux-appservice#133]
Hello,

I followed the directions [provided here](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_multisite_installation.md) to configure a Subdomain-based multisite. However, this appeared to have no effect. The installation is still not a multisite, as shown by navigating to /wp-admin/network/ and being presented with the message "Multisite support is not enabled.".

More specifically, I:
- Launched an app service with the mcr.microsoft.com/appsvc/wordpress-alpine-php:8.3 image.
- Configured WordPress to the point of logging into the backend, [as instructed here](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/how-to-set-up-a-new-wordpress-website-on-azure-app-service/ba-p/3729150) which is linked-to from the documentation above.
- Added the following App Settings
> - WORDPRESS_MULTISITE_CONVERT | true
> - WORDPRESS_MULTISITE_TYPE | subdomain
> - CUSTOM_DOMAIN | _mydomain.com_
- Restarted the container.

I am presented with my initialized WP instance. I can log into the backend. It is not a multisite.

Did I miss the window to configure this somehow?

**Comment by rabollin** [comment]
@ZubaeyrMSFT - Please review this issue and respond.

**Comment by samrueby** [comment]
@ZubaeyrMSFT your help would be greatly appreciated.

**Comment by samrueby** [comment]
Found the answer on an [unrelated page](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_application_settings.md#one-time-application-settings): 
>Configurations that are used as a 'one-time' change and are applied just once. Any additional changes to these App Settings after the app has been deployed or configured won't re-configure or update your WordPress site.

The documentation I mentioned above make it sound like WordPress should be setup first and then `WORDPRESS_MULTISITE_CONVERT` configured.

**Comment by ZubaeyrMSFT** [comment]
Hello @samrueby,

Can you please email on wordpressonazure@microsoft.com? Please mention the following details too:

1. App Service name.
2. Are you using Azure Front Door?
3. Can you see multisite configuration code block defined in wp-config.php? If so, please share the code block. It should look something like this:

```
define( 'WP_ALLOW_MULTISITE', true );
define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', true );
$base = '/';
define( 'DOMAIN_CURRENT_SITE', $http_protocol . $_SERVER['HTTP_HOST'] );
define( 'PATH_CURRENT_SITE', '/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );
```
4. Share the contents of file /home/wp-locks/wp_deployment_status.txt file. You can view the file from SCM site of your App Service. (https://**<appname>**.scm.azurewebsites.net/newui/webssh)

5. Please re-check if you have mapped the custom domain and necessary sub-domains to your App Service: https://learn.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-domain?tabs=root%2Cazurecli

6. If you are using AFD, please ensure you have mapped the custom domain to AFD endpoint instead of App Service. https://learn.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-add-custom-domain
