### ISSUE TITLE
WordPress editor page does not show media files from blob storage

### ISSUE THREAD

**Issue by victorlin** [Azure/wordpress-linux-appservice#160]
From [wordpress_azure_blob_storage.md](https://github.com/Azure/wordpress-linux-appservice/blob/7e593b214c040afbf2c9937fb365f4d870b9b425/WordPress/wordpress_azure_blob_storage.md):

> You can also free up disk space on App Service by deleting the Media files in wp-content/uploads folder, if they are already stored in Blob Storage. It is however recommended to ensure Blob Storage has all files present in App Service before deleting.

I just tried this and noticed that it breaks media previews in the editor, which references `{SITE_URL}/wp-content/uploads` and not `{AZURE_CDN_URL}/{BLOB_CONTAINER}/wp-content-uploads`. Opening the preview in a new tab works fine, but the content manager of my site relies on the real-time preview within the editor.

Questions:

1. Is there any way to configure W3 Total Cache to inject the CDN endpoints on the editor page in addition to the actual site? I've also asked this on the plugin's repo: https://github.com/BoldGrid/w3-total-cache/issues/923
2. If not, are there any other workarounds to have working media previews in the editor without keeping files on App Service disk?

**Comment by ZubaeyrMSFT** [comment]
Hello @victorlin, seems like this is an W3 Total Cache plugin issues and I believe you have already raised an issue there. Closing this issue here.

**Comment by KloudstackHosting** [comment]
Hi @victorlin


So it's the Permalink that is not functioning correctly because it attempts to locate the file on the local file system. However, the File URL is working as expected and correctly points to the file in Blob Storage, right?


In WordPress, the _wp_attached_file meta key (stored in the wp_postmeta table) is responsible for holding the relative path to the uploaded file. This path is critical for WordPress to reference and serve media files.

**Key Notes:**

1. When the Yoast SEO plugin is installed, it modifies the behavior of attachment links by converting them to direct image URLs rather than WordPress attachment pages.

2. Plugins such as W3 Total Cache and WebP converters depend on the _wp_attached_file meta key to locate files and generate alternative formats (e.g., WebP).

Hope this helps...
