### ISSUE TITLE
Root password?

### ISSUE THREAD

**Issue by SamNicholsCricksoft** [Azure/wordpress-linux-appservice#178]
Hi, 

sorry to create an issue on your GitHub for this, I just don't know how else to ask this question.

I'm using the bash terminal in azure advanced tools to ssh to my linux WordPress app service, I'm trying to install ffmpeg onto the server but I need the root password to be able to so, would you know what this would be set to?

Thanks 
Sam

**Comment by samrueby** [comment]
Hi,

When using the bash terminal or SSH  in the Azure advanced tools, you are executing as root. You can prove this by running the command `whoami`, where you will see the output "root". If you are for some reason prompted for the password, you are able to find this by clicking on "Menu" at the bottom-left of the Kudu SSH UI and choose "Credentials", it will input the root password, which is **Docker!**

Do note that if you install ffmpeg, or any other software on the server, it will not persist. This is because the server runs as a container, and when the container restarts, it will boot from a fresh image. In order to maintain ffmpeg, you should add the commands you use to install/configure to the startup script found in /home/dev/startup.sh. Read more here: https://github.com/Azure/wordpress-linux-appservice/blob/c0b412da1632d43cee53b83d0f9a7a8831f99277/WordPress/running_post_startup_scripts.md
