### ISSUE TITLE
Wordpress app service deployment fails at MySQL fexibleserver deployment step

### ISSUE THREAD

**Issue by Shafeeqts89** [Azure/wordpress-linux-appservice#24]
Hi Team,

We are trying to deploy WordPress on the azure app service and it keeps failing at the MySQL flexible server deployment step. We tried it on West Europe and North Europe regions with different subscriptions.

![image](https://user-images.githubusercontent.com/60779307/199529968-05d857ad-c7a5-4abc-a166-36358f8bac57.png)

Any help would be appreciated.

Thanks.

**Comment by rabollin** [comment]
Hi @Shafeeqts89 - thank you for reaching out. Deployment is failing due to MySQL Flexible server provisioning that was occuring due to an ongoing  AKV Sev1 outage :
 [Outage 346134987](https://portal.microsofticm.com/imp/v3/outages/details/346134987/home) : Certificate enrollment and renewal requests to all CA's behind OneCert are experiencing timeouts and throttling in all clouds, all regions

**Comment by Shafeeqts89** [comment]
@rabollin Thanks for the information, It works now!

**Comment by rabollin** [comment]
Issue was resolved when the upstream issue was fixed.
