### ISSUE TITLE
How to use wp cli?

### ISSUE THREAD

**Issue by kubami** [Azure/wordpress-linux-appservice#72]
I see wpcli is installed in the service but I cannot seem to make it work.

```
/var/www/wordpress# wp --allow-root plugin list

Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /var/www/wordpress/wp-includes/class-wpdb.php on line 2019
Error: `No such file or directory`
Error establishing a database connection
```

I presume it has something to do with the env variables for the db connection not being present in the shell I am in?

I open the ssh connection through Web App -> App Service plan -> Development Tools -> SSH.

**Comment by rabollin** [comment]
Currently issue is being investigated, there are some challenges with user permissions in accessing wp-cli.

**Comment by ZubaeyrMSFT** [comment]
@kubami 

If you are running interactively via **WebSSH**, then you need to first update the **wp-config.php** file with database connection details. The reason is that database connection details are wired into wp-config.php file from the Application Settings and those are accessible by the thread that starts the container. 

Look for this block of code in wp-config.php file

```
$connectstr_dbhost = getenv('DATABASE_HOST');                                                                
$connectstr_dbname = getenv('DATABASE_NAME');                                                                
$connectstr_dbusername = getenv('DATABASE_USERNAME');                                                        
$connectstr_dbpassword = getenv('DATABASE_PASSWORD');
```
Comment it out and add a new block with actual database connection details.
```
//$connectstr_dbhost = getenv('DATABASE_HOST');                                                                
//$connectstr_dbname = getenv('DATABASE_NAME');                                                                
//$connectstr_dbusername = getenv('DATABASE_USERNAME');                                                        
//$connectstr_dbpassword = getenv('DATABASE_PASSWORD');
 
$connectstr_dbhost = 'servername.mysql.database.azure.com';                                                    
$connectstr_dbname = 'database_name';                                                              
$connectstr_dbusername = 'db_username';                                                        
$connectstr_dbpassword = 'db_password';
```

Now try running the below sample wp-cli commands form WebSSH console.
```
wp help --path=/home/site/wwwroot --allow-root
wp plugin list --path=/home/site/wwwroot --allow-root 
```
 
**Note:** You can retrieve database connection details from your App Service dashboard in Azure Portal. 
_(Configuration -> Application Settings -> Advanced edit)_

**Comment by rabollin** [comment]
@kubami - Can you confirm if your issue is resolved and can close this GH issue.

**Comment by ZubaeyrMSFT** [comment]
@kubami
WP-CLI is now fully enabled in production. You can now access and use it from SSH console of your SCM site.

Please refer to the following document for more details:
https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/how_to_use_wpcli_tool.md
