### ISSUE TITLE
WP debug.log

### ISSUE THREAD

**Issue by emmigereb** [Azure/wordpress-linux-appservice#81]
I can´t get debug.log working in wp-content.
I have the following in my wp-config.php:
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
define( 'WP_DEBUG_LOG', true );

But no debug.log is showing up.

**Comment by rabollin** [comment]
This is a bug with existing system : https://msazure.visualstudio.com/Antares/_workitems/edit/24122415

**Comment by dumbphoneboostcoder** [comment]
Any update on this?

**Comment by v3lli** [comment]
so far we have tried to add an ini uning PHP_INI_SCAN_DIR, this part was successful as we got the ini to be loaded in this ini we added the following settings:

log_errors = true;
error_log = "/home/site/wwwroot/errors.log"
max_file_uploads = 50

and on checking the phpinfo page we noticed that we were able to change the value for max_file_uploads from the default value of 20 to 50 

Proving that this ini file was read but the change for error_log didnt take effect as the value wsas still set at 
/var/log/fpm-php.www.log

and on checking this directory /var/log/fpm-php.www.log we were unable to locate the file which it points to as it does not exist.

however all this works as expected when using a php blessed image instead of the wordpress on appservice markeptplace offering

**Comment by ZubaeyrMSFT** [comment]
@v3lli The issue has been fixed and deployed to production. Please restart your App for it to reflect. The logs would now be available at **/var/log/php-fpm/php-fpm.www.log**

Here is the documentation on how to enable debug logs with WordPress:
https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/enabling_debug_logs_for_wordpress.md

**Comment by v3lli** [comment]
***@***.***
